name:                parallel-test
version:             0.1.0.0
synopsis:            Initial project template from stack
description:         Please see README.md
homepage:            https://github.com/dktn/parallel-test#readme
license:             MIT
author:              Adam Szlachta
maintainer:          adam.szlachta@gmail.com
copyright:           Apache 2.0
ghc-options:         -Wall

dependencies:
  - base >= 4.7 && < 5
  - deepseq
  - text
  - containers
  - criterion
  - monad-par
  - parallel
  - lvish


library:
  source-dirs:        src

default-extensions:
  - OverloadedStrings
  - NoMonomorphismRestriction
  - DeriveGeneric

executables:
  parallel-test-exe:
    main:             Main.hs
    source-dirs:      app
    dependencies:
      - parallel-test
      - ekg
    ghc-options:      -threaded -rtsopts -with-rtsopts=-N -with-rtsopts=-T
  parallel-test-bench:
    main:             Benchmark.hs
    source-dirs:      bench
    dependencies:
      - parallel-test
    ghc-options:      -threaded -rtsopts -with-rtsopts=-N -with-rtsopts=-T

tests:
  parallel-test-test:
    # cpp-options: -DTEST
    main: Main.hs
    source-dirs:
      - test
      - src
    dependencies:
      - parallel-test
      - tasty
      - tasty-quickcheck
      - tasty-smallcheck
      - tasty-hunit
      # - hspec == 2.*
      # - QuickCheck
      # - temporary
      # - mockery >= 0.3
      # - interpolate
      # - aeson-qq
      # - aeson >= 0.10
    ghc-options: -threaded -rtsopts -with-rtsopts=-N

